/*
 * User_interface.h
 *
 * Created: 06-Oct-24 5:50:22 PM
 *  Author: 
 */ 


#ifndef USER_INTERFACE_H_
#define USER_INTERFACE_H_

#define MAX_NUM_OF_USERS	 5



/* EEPROM LOCATIONS */

#define	USER_1_USERNAME_LOC 8 //FIRST USERNAME LOCATION
#define	USER_1_PASSWORD_LOC 32 //FIRST PASSWORD LOCATION

#define ADDRESS_NUM_OF_USERS 500 //LOCATION WHERE THE CURRENT NUMBER OF USERS IS STORED AND UPDATED

/* CONFIGURATIONS */
#define USER_USERNAME_SIZE  4 
#define USER_PASSWORD_SIZE  4


/** FUNCTIONS **/
u8 USER_LogIn();
void USER_MODE_Init();


#endif /* USER_INTERFACE_H_ */